name: Sample 4 Shared Deploy

on:
  workflow_dispatch:

jobs:
  deployInfraShared:
    name: Deploy Infras (Shared)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: sample3/shared
    steps:
      - uses: actions/checkout@v2
      
      - uses: hashicorp/setup-terraform@v1
        name: Setup Terraform
      - run: |
          terraform init -backend-config="access_key=${{ secrets.TERRAFORM_STATE_STORAGE_ACCESS_KEY }}"
        name: Terraform Init
      - run: |
          terraform apply -auto-approve -var 'location=eastus' -var 'client_secret=${{ secrets.TERRAFORM_SP_CLIENT_SECRET }}'
        name: Terraform Apply