name: Sample 4 App

on:
  push:
    branches:
      - 'main'
    paths:
      - sample4/app/*
      - .github/workflows/sample4_app.yaml
  workflow_dispatch:

jobs:
  publish:
    name: Publish App
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: sample4/app
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.x.x

      - name: Build App
        run: |
          dotnet build --output ../output
          ls -l ../output

      #- name: Deploy SWA
      #  uses: Azure/static-web-apps-deploy@v1
      #  with:
      #    azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
      #    action: upload
      #    app_location: ./sample4/app
      #    repo_token: ${{ secrets.GITHUB_TOKEN }}
      #    app_artifact_location: sample4/app/wwwroot
